### PR TITLE
build docker image from source

### PR DESCRIPTION
**Pull request by ancho**
Lets get things started. I'm not very familiar with docker image building.
So any feedback and suggestion is welcome :)

This is a multistaged build directly from source using the jbake repository as git submodule.
It uses the official openjdk alpine images.

### CODE REVIEW

**Comment by ancho** [comment]
Thinking about this solution. Would it make sense to place the Dockerfile into jbake core?
That way the build could be automated directly from dockerhub with a new git tag.

**Comment by jonbullock** [comment]
I haven't had chance to look at this yet but your suggestion sounds logical to me.

**Comment by nikkushankar** [comment]
I think It will make more sense to use a full feature webserver to front the generated site. Here is a quick demo. 
https://github.com/nikkushankar/jbake-docker-image

**Comment by manikmagar** [comment]
@ancho @jonbullock Yes, I think building docker image as a part of core build makes sense. We can then ensure that latest image is also released when a core is released. Image should be built on top of the binaries pushed to the repositories.

**Comment by jonbullock** [comment]
Superseded  by jbake-org/jbake#681

**Pull request closed without merging**
