### PR TITLE
Initial implementation of Dockerfile

### PR DESCRIPTION
**Pull request by michalharakal**
Add initial version of docker file for JBake with a separated builder and runner image

### CODE REVIEW

**Comment by michalharakal** [comment]
I have missed, that there is already existing pull request for creating docker image. So if it is unnecessary just close the PR.

My focus was more to have just command line tool to render site as part of build chain in cloud, instead of dockerizing my local environment. Running server with this docker image even doesn't work and I am not sure if it is possible at all to react on changes in files on mounted volume.

**Comment by jonbullock** [comment]
Thanks for taking the time to submit this PR. I'm using Docker elsewhere at the moment so should be able to comment meaningfully on this soon.

**Comment by michalharakal** [comment]
@jonbullock If you consider Docker, it would be nice to have an "official" image on docker hub too. It should be possible with Github actions. [Github publishing Docker images](https://docs.github.com/en/actions/guides/publishing-docker-images)

**Comment by jonbullock** [comment]
Thanks for the pointer @michalharakal I'm fairly sure I've acquired a group name on Docker Hub for JBake.

**Comment by jonbullock** [comment]
I'm going to close this PR as it makes more sense for the Dockerfile to reside in the main JBake repo (see jbake-org/jbake#681) but thanks again for taking the time to work on this, it's directly responsible for getting this moving again. I have acquired the jbake name on Docker Hub so I'll get an official image up there too.

**Pull request closed without merging**
